apiVersion: v1
kind: Pod
metadata:
  name: mavenweb-app
  labels:
    app: mavenwebapp
  namespace: test-ns
spec:
  containers:
  - name: mavenwebappcontainer
    image: docker8955/maven-web-app:1
    ports:
    - containerPort: 8080
  - name: nginxcontainer
    image: nginx
    ports:
    - targetPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mavenwebsvc
  namespace: test-ns
spec:
  type: NodePort
  ports:
  - name: mavenweb-app
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: nginx
    port: 80
    targetPort: 80
  selector:
    app: mavenwebapp #these are labels attach to the pod 