apiVersion: apps/v1
kind:  Deployment
metadata:
  name: nginx-deployment
  namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
  ## indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50% #max no of pod unavailable during update process
      maxSurge: 10% #max new no of pod get during this proces
  minReadySeconds: 30  #it will wait 30 sec after creation of new pod then it will delete old pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: name
                operator: In
                values:
                - nginx
      containers:
      - name: nginxappcontainer
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80

#kubectl get nodes --show-labels
#kubectl label node <nodeName> name=nginx