apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpathpv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/mongopv
  persistentVolumeReclaimPolicy: Recycle


  #3types of ReclaimPolicy:- Delete,Retain,Recycle