apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdaemonset
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports: 
  - port: 80
    targetPort: 80


