apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: test-ns
  labels:
    app: nginx
spec:
  tolerations:
  - key: kamlesh
    value: hatepod
    operator: Equal
    effect: NoSchedule
  containers:
  - name: nginx-app-container
    image: nginx
    ports:
    - containerPort: 80

    
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80

#kubectl taint node ip-192-168-0-156  node=hatepod:NoSchedule
#NoSchedule
#NoExecute
#PreferNoSchedule